### ISSUE TITLE
Feat: add error for chat functionality

### ISSUE THREAD

**Issue by josh-hrnndz** [josh-hrnndz/realtime-chat-app#12]
## 📝 Description

Add an error if the chat functionality is not connected successfully. In addition, add dotenv package for handling server ports.

## ⚙️ Component

- `chat.page.dart`
- socket repository
- socket cubit
- `chat.widget.dart`
- `response.model.dart`
- `strings.dart`
- `api.service.dart`

## 📋 Todo:

- [x] Add an error display if message is not send successfully
- [x] Add isFailed attribute on response model
- [x] Add setResponseStatus in socket repository
- [x] Add dotenv package and implement it on `api.service.dart`
