### ISSUE TITLE
Feat: add roomName attribute

### ISSUE THREAD

**Issue by josh-hrnndz** [josh-hrnndz/realtime-chat-app#14]
## 📝 Description

- With the recent change in the websocket server, the client now requires the room name when emitting a message. 

## ⚙️ Component

- `response.model.dart`
- `socket.repository.impl.dart`
- `socket_cubit.dart`
- `api.service.dart`

## 📋 Todo:

- [x] Add roomName attribute in responseModel
- [x] Add roomName attribute in api service 
- [x] Create a getter and setter for roomName attribute in the repository
- [x] Set the roomName retrieved on connect function in `socket_cubit.dart`
