### ISSUE TITLE
Feat: Create chat page UI

### ISSUE THREAD

**Issue by josh-hrnndz** [josh-hrnndz/realtime-chat-app#3]
## 📝 Description
- There should be a chat page where the main functionality of the app will be located.

## ⚙️ Component
- `chat.page.dart`
- `router.dart`
- `routes.dart`

## 📋 Todo:

- [x] Create chat page UI
- [x] Add chat page to router
- [x] Add chat page route string
