### ISSUE TITLE
Feat: add connect functionality after clicking start button

### ISSUE THREAD

**Issue by josh-hrnndz** [josh-hrnndz/realtime-chat-app#5]
## 📝 Description

The start page is the first step in looking for strangers to talk to in this app. With this, the button on the start page should trigger the connect function of the websocket which should navigate the user to the chat page where the conversation will happen. 
## ⚙️ Component

- cubit and state for websocket functions
- `di.dart`
- repository for websocket functions
- source for websocket functions
- start page
- `failures.dart`
- `router.dart`
- `api.service.dart`

## 📋 Todo:

- [x] Create an api service for the socket.io functions
- [x] Create a cubit, state, repository and source for websocket functions
- [x] Add all the necessary dependencies to `di.dart`
- [x] Create connect function for websocket connection
- [x] Trigger the connect function using the start page button
- [x] Add dartz package for error handling
