### ISSUE TITLE
Feat: add loading modal for start page

### ISSUE THREAD

**Issue by josh-hrnndz** [josh-hrnndz/realtime-chat-app#7]
## 📝 Description
- To make the app more pleasant when waiting for an asynchronous task such as waiting for the server to connect the user, there should be some sort of a loading screen to be displayed in between page navigation.

## ⚙️ Component

- loading screen

## 📋 Todo:

- [x] Create a loading screen that will be displayed after clicking the start page button
- [x] Add the loading screen display on the start page listener
- [x] Add a 1 second delay to the loading screen
