### ISSUE TITLE
Feat: chat page chat functionality

### ISSUE THREAD

**Issue by josh-hrnndz** [josh-hrnndz/realtime-chat-app#9]
## 📝 Description

After a successful connection to the websocket server, the app should now be able to send and receive messages which will be stored in a list kept in the repository of the app. 

## ⚙️ Component

- `socket_cubit.dart`
- `socket_state.dart`
- `socket.repository.dart`
- `socket.repository.impl.dart`
- `socket.source.dart`
- `socket.source.impl.dart`
- `chat.page.dart`

## 📋 Todo:

- [x] create send message function
- [x] add websocket server listener to receive messages
- [x] display messages in the chat app page
